# Generated by Django 6.0.5 on 2026-05-19 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_address_to_street(apps, schema_editor):
    Tutor = apps.get_model('petcad', 'Tutor')
    for tutor in Tutor.objects.all():
        if tutor.address and not tutor.street:
            tutor.street = tutor.address
            tutor.save(update_fields=['street'])


class Migration(migrations.Migration):

    dependencies = [
        ('petcad', '0002_person_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Tutor',
        ),
        migrations.AlterModelTable(
            name='tutor',
            table='petcad_person',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tutor_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='tutor',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='tutor',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.RunPython(migrate_address_to_street, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tutor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='animals_notes',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Macho'), (1, 'Fêmea')]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='animals',
                to='petcad.tutor',
            ),
        ),
    ]
