# Generated by Django 6.0.5 on 2026-05-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcad', '0003_rename_person_to_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
    ]
