# Generated by Django 6.0.5 on 2026-05-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcad', '0004_remove_tutor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vaccine_type', models.CharField(blank=True, choices=[('obrigatoria', 'Obrigatória'), ('recomendada', 'Recomendada'), ('opcional', 'Opcional')], default='', max_length=20)),
                ('application_date', models.DateField()),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='petcad.animal')),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
